### ISSUE TITLE
collabvm sucks dick

### ISSUE THREAD

**Issue by ghost** [computernewb/collab-vm#2]
Title.

**Comment by dartzcn** [comment]
I consider sucking dick an art form. When someone tells me to suck his dick I view it as an honor and a privilege. Not to mention an opportunity to show off my unparalleled dick sucking skills. Most of the time, the man puts up quite the struggle and yells at me that he didn't mean it literally. But I see straight through that ruse. When I finally free that dick from his pants and place it inside my mouth everything changes. The look of blissful ecstasy on his face reaffirms what I already hold true in my heart. This is what I was born to do. Dick is my medium and I am it's master. No homo.

**Comment by elijahr2411** [comment]
@dartzcn modern shakespeare, brought tears to my eyes. very homo

**Comment by enmanuel46** [comment]
peak copypasta material
